  Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    config.vm.network "private_network", ip: "192.168.33.10" # Definindo um IP para acessar posteriormente
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024 # Minha quantidade de memória RAM
      vb.cpus = 2 # Minha quantidade de núcleos
    end
    
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nginx
      echo "Oi testando aqui" | sudo tee /var/www/html/index.html
    SHELL
  end