Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.define "dhcp-server" do |server|
    server.vm.network "private_network", ip: "192.168.33.20"
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y isc-dhcp-server
      echo "INTERFACESv4=\"enp0s8\"" | sudo tee /etc/default/isc-dhcp-server
      sudo systemctl restart isc-dhcp-server
    SHELL
  end
end